### ISSUE TITLE
Installing dependencies: issue with molecule-tda

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofdscribe#277]
Hey Kevin,

I'm trying to install `mofdscribe` and all the dependencies. I'm having some trouble installing `molecule-tda`. I cloned the repo and `pip install .`'d it and got back the following. This is on WSL with Python 3.8. I'm not too familiar with `poetry` so am still trying to figure this one out.

```
Processing /mnt/c/Users/asros/github/molecule-tda
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/home/arosen/anaconda3/envs/mofs/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/arosen/anaconda3/envs/mofs/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/arosen/anaconda3/envs/mofs/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-gobwb3l6/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 44, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-gobwb3l6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 58, in __init__
          super(WheelBuilder, self).__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-gobwb3l6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py", line 85, in __init__
          self._module = Module(
        File "/tmp/pip-build-env-gobwb3l6/overlay/lib/python3.8/site-packages/poetry/core/masonry/utils/module.py", line 63, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package molecule-tda
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by kjappelbaum** [comment]
shall we close this issue? I think the installation is a bit simpler now, even though it still requires manually conda installs to have the full functionality

**Comment by arosen93** [comment]
Yes, close!

**Comment by kjappelbaum** [comment]
reopening as @sauradeep93 reported issues on Mac
