### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'network'

### ISSUE THREAD

**Issue by KP-303** [kjappelbaum/mofdscribe#450]
When trying to featurise a MOF I get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'network'

Running on a Mac M1 Pro with Ventura 13.3.1 and Python 3.10.8.

I installed Mofdescribe by cloning from github and doing pip install -e .

I'm trying to get the pore diameters descriptors. Code looks like this:

'''
from mofdscribe.featurizers.pore.geometric_properties import PoreDiameters
parser = CifParser('test.cif')
mof = parser.get_structures()[0]
featuriser=PoreDiameters()
features=featuriser.featurize(mof)
'''

Full error message:

Traceback (most recent call last):
  
  File "...", line 87, 
    features=featuriser.featurize(mof)

  File ".../mofdscribe/src/mofdscribe/featurizers/base.py", line 107, in featurize
    return self._featurize(structure)

  File ".../mofdscribe/src/mofdscribe/featurizers/pore/geometric_properties.py", line 196, in _featurize
    result = run_zeopp(s, ["-res"], _parse_res_zeopp, self.ha)

  File ".../mofdscribe/src/mofdscribe/featurizers/pore/geometric_properties.py", line 72, in run_zeopp
    _ = subprocess.run(  # nosec

  File ".../lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:

  File ".../lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File ".../lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'network'

Thanks

**Comment by kjappelbaum** [comment]
Hi 👋🏽 

Thanks for trying mofdscribe. 

You ran into a missing dependency, probably because you installed via pip, which does not install all dependencies by default. 
In this case, you miss `zeo++`, which you can install via `conda install zeopp-lsmo` from `conda-forge`. We specifically made a port to also make this one work for m1 macs.

All the best,
Kevin

**Comment by KP-303** [comment]
Thanks that works now. By the way, I installed via cloning because when I install via conda and try and run the code it says moleculetda is not found, and I am having trouble installing moleculetda. I can raise this as a separate issue if you want.

**Comment by ngkayjay** [comment]
> Thanks that works now. By the way, I installed via cloning because when I install via conda and try and run the code it says moleculetda is not found, and I am having trouble installing moleculetda. I can raise this as a separate issue if you want.

Did you manage to find a solution for the missing moleculetda from a conda install? Thanks!

**Comment by kjappelbaum** [comment]
So `moleculetda` worked neither via PyPi nor conda?
